# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_1_0/design_1_zynq_ultra_ps_e_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_3/design_1_smartconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_3 || ORIG_REF_NAME==design_1_smartconnect_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_4 || ORIG_REF_NAME==design_1_smartconnect_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_5/design_1_smartconnect_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_5 || ORIG_REF_NAME==design_1_smartconnect_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_3_0/design_1_smartconnect_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_3_0 || ORIG_REF_NAME==design_1_smartconnect_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_4_0/design_1_smartconnect_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_4_0 || ORIG_REF_NAME==design_1_smartconnect_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_4_2/design_1_smartconnect_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_4_2 || ORIG_REF_NAME==design_1_smartconnect_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Dense_0_0/design_1_Dense_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Dense_0_0 || ORIG_REF_NAME==design_1_Dense_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_My_Conv_0_1/design_1_My_Conv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_My_Conv_0_1 || ORIG_REF_NAME==design_1_My_Conv_0_1} -quiet] -quiet

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/design_1_ooc.xdc
