# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/design_1_smartconnect_4_2.xci
# IP: The module: 'design_1_smartconnect_4_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/bd_486c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_0/bd_486c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_2/bd_486c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_3/bd_486c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_4/bd_486c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_5/bd_486c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_6/bd_486c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_7/bd_486c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_8/bd_486c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_9/bd_486c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_10/bd_486c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_11/bd_486c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_12/bd_486c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_5/bd_486c_s00a2s_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_6/bd_486c_sarn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_7/bd_486c_srn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_8/bd_486c_sawn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_9/bd_486c_swn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_10/bd_486c_sbn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_11/bd_486c_m00s2a_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_4_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/design_1_smartconnect_4_2.xci
# IP: The module: 'design_1_smartconnect_4_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/bd_486c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_0/bd_486c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_2/bd_486c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_3/bd_486c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_4/bd_486c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_5/bd_486c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_6/bd_486c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_7/bd_486c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_8/bd_486c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_9/bd_486c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_10/bd_486c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_11/bd_486c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_12/bd_486c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_1/bd_486c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_5/bd_486c_s00a2s_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_6/bd_486c_sarn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_7/bd_486c_srn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_8/bd_486c_sawn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_9/bd_486c_swn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_10/bd_486c_sbn_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/bd_0/ip/ip_11/bd_486c_m00s2a_0_ooc.xdc

# XDC: d:/Learning/CNN_Accelerator/Project/Vivado_Project/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_smartconnect_4_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_4_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
