// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module My_Conv_Write_Output_F_Pipeline_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_84,
        output_buffer_0_address1,
        output_buffer_0_ce1,
        output_buffer_0_we1,
        output_buffer_0_d1,
        output_buffer_4_address1,
        output_buffer_4_ce1,
        output_buffer_4_we1,
        output_buffer_4_d1,
        output_buffer_8_address1,
        output_buffer_8_ce1,
        output_buffer_8_we1,
        output_buffer_8_d1,
        output_buffer_12_address1,
        output_buffer_12_ce1,
        output_buffer_12_we1,
        output_buffer_12_d1,
        output_buffer_16_address1,
        output_buffer_16_ce1,
        output_buffer_16_we1,
        output_buffer_16_d1,
        output_buffer_20_address1,
        output_buffer_20_ce1,
        output_buffer_20_we1,
        output_buffer_20_d1,
        output_buffer_24_address1,
        output_buffer_24_ce1,
        output_buffer_24_we1,
        output_buffer_24_d1,
        output_buffer_28_address1,
        output_buffer_28_ce1,
        output_buffer_28_we1,
        output_buffer_28_d1,
        empty,
        Out_Tc_Min_cast_cast_cast
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] empty_84;
output  [8:0] output_buffer_0_address1;
output   output_buffer_0_ce1;
output  [3:0] output_buffer_0_we1;
output  [31:0] output_buffer_0_d1;
output  [8:0] output_buffer_4_address1;
output   output_buffer_4_ce1;
output  [3:0] output_buffer_4_we1;
output  [31:0] output_buffer_4_d1;
output  [8:0] output_buffer_8_address1;
output   output_buffer_8_ce1;
output  [3:0] output_buffer_8_we1;
output  [31:0] output_buffer_8_d1;
output  [8:0] output_buffer_12_address1;
output   output_buffer_12_ce1;
output  [3:0] output_buffer_12_we1;
output  [31:0] output_buffer_12_d1;
output  [8:0] output_buffer_16_address1;
output   output_buffer_16_ce1;
output  [3:0] output_buffer_16_we1;
output  [31:0] output_buffer_16_d1;
output  [8:0] output_buffer_20_address1;
output   output_buffer_20_ce1;
output  [3:0] output_buffer_20_we1;
output  [31:0] output_buffer_20_d1;
output  [8:0] output_buffer_24_address1;
output   output_buffer_24_ce1;
output  [3:0] output_buffer_24_we1;
output  [31:0] output_buffer_24_d1;
output  [8:0] output_buffer_28_address1;
output   output_buffer_28_ce1;
output  [3:0] output_buffer_28_we1;
output  [31:0] output_buffer_28_d1;
input  [2:0] empty;
input  [30:0] Out_Tc_Min_cast_cast_cast;

reg ap_idle;
reg output_buffer_0_ce1;
reg[3:0] output_buffer_0_we1;
reg output_buffer_4_ce1;
reg[3:0] output_buffer_4_we1;
reg output_buffer_8_ce1;
reg[3:0] output_buffer_8_we1;
reg output_buffer_12_ce1;
reg[3:0] output_buffer_12_we1;
reg output_buffer_16_ce1;
reg[3:0] output_buffer_16_we1;
reg output_buffer_20_ce1;
reg[3:0] output_buffer_20_we1;
reg output_buffer_24_ce1;
reg[3:0] output_buffer_24_we1;
reg output_buffer_28_ce1;
reg[3:0] output_buffer_28_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] empty_261_fu_433_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] tmp_reg_450;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] Out_Tc_Min_cast_cast_cast_cast_cast_fu_232_p1;
reg   [63:0] Out_Tc_Min_cast_cast_cast_cast_cast_reg_459;
wire   [63:0] p_cast_fu_263_p1;
wire    ap_block_pp0_stage0;
reg   [63:0] empty_257_fu_78;
wire   [63:0] empty_260_fu_275_p2;
wire    ap_loop_init;
wire   [3:0] mask676_fu_293_p2;
wire   [3:0] mask674_fu_312_p2;
wire   [3:0] mask672_fu_331_p2;
wire   [3:0] mask670_fu_350_p2;
wire   [3:0] mask668_fu_369_p2;
wire   [3:0] mask666_fu_388_p2;
wire   [3:0] mask664_fu_407_p2;
wire   [3:0] mask678_fu_426_p2;
wire  signed [62:0] Out_Tc_Min_cast_cast_cast_cast_fu_228_p1;
wire   [8:0] tmp_s_fu_248_p4;
wire   [8:0] empty_259_fu_258_p2;
wire   [0:0] empty_258_fu_244_p1;
wire   [1:0] udiv675_cast_cast_fu_281_p3;
wire   [3:0] empty_268_fu_289_p1;
wire   [1:0] udiv673_cast_cast_fu_300_p3;
wire   [3:0] empty_267_fu_308_p1;
wire   [1:0] udiv671_cast_cast_fu_319_p3;
wire   [3:0] empty_266_fu_327_p1;
wire   [1:0] udiv669_cast_cast_fu_338_p3;
wire   [3:0] empty_265_fu_346_p1;
wire   [1:0] udiv667_cast_cast_fu_357_p3;
wire   [3:0] empty_264_fu_365_p1;
wire   [1:0] udiv665_cast_cast_fu_376_p3;
wire   [3:0] empty_263_fu_384_p1;
wire   [1:0] udiv663_cast_cast_fu_395_p3;
wire   [3:0] empty_262_fu_403_p1;
wire   [1:0] udiv677_cast_cast_fu_414_p3;
wire   [3:0] empty_269_fu_422_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

My_Conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_257_fu_78 <= 64'd0;
        end else if (((empty_261_fu_433_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_257_fu_78 <= empty_260_fu_275_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Out_Tc_Min_cast_cast_cast_cast_cast_reg_459[62 : 0] <= Out_Tc_Min_cast_cast_cast_cast_cast_fu_232_p1[62 : 0];
    end
end

always @ (*) begin
    if (((empty_261_fu_433_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_0_ce1 = 1'b1;
    end else begin
        output_buffer_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd4))) begin
        output_buffer_0_we1 = mask664_fu_407_p2;
    end else begin
        output_buffer_0_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_12_ce1 = 1'b1;
    end else begin
        output_buffer_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd7))) begin
        output_buffer_12_we1 = mask670_fu_350_p2;
    end else begin
        output_buffer_12_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_16_ce1 = 1'b1;
    end else begin
        output_buffer_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd0))) begin
        output_buffer_16_we1 = mask672_fu_331_p2;
    end else begin
        output_buffer_16_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_20_ce1 = 1'b1;
    end else begin
        output_buffer_20_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd1))) begin
        output_buffer_20_we1 = mask674_fu_312_p2;
    end else begin
        output_buffer_20_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_24_ce1 = 1'b1;
    end else begin
        output_buffer_24_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd2))) begin
        output_buffer_24_we1 = mask676_fu_293_p2;
    end else begin
        output_buffer_24_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_28_ce1 = 1'b1;
    end else begin
        output_buffer_28_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd3))) begin
        output_buffer_28_we1 = mask678_fu_426_p2;
    end else begin
        output_buffer_28_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_4_ce1 = 1'b1;
    end else begin
        output_buffer_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd5))) begin
        output_buffer_4_we1 = mask666_fu_388_p2;
    end else begin
        output_buffer_4_we1 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_buffer_8_ce1 = 1'b1;
    end else begin
        output_buffer_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_450 == 3'd6))) begin
        output_buffer_8_we1 = mask668_fu_369_p2;
    end else begin
        output_buffer_8_we1 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Out_Tc_Min_cast_cast_cast_cast_cast_fu_232_p1 = $unsigned(Out_Tc_Min_cast_cast_cast_cast_fu_228_p1);

assign Out_Tc_Min_cast_cast_cast_cast_fu_228_p1 = $signed(Out_Tc_Min_cast_cast_cast);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_258_fu_244_p1 = empty_257_fu_78[0:0];

assign empty_259_fu_258_p2 = (empty_84 + tmp_s_fu_248_p4);

assign empty_260_fu_275_p2 = (empty_257_fu_78 + 64'd1);

assign empty_261_fu_433_p2 = ((empty_260_fu_275_p2 < Out_Tc_Min_cast_cast_cast_cast_cast_reg_459) ? 1'b1 : 1'b0);

assign empty_262_fu_403_p1 = udiv663_cast_cast_fu_395_p3;

assign empty_263_fu_384_p1 = udiv665_cast_cast_fu_376_p3;

assign empty_264_fu_365_p1 = udiv667_cast_cast_fu_357_p3;

assign empty_265_fu_346_p1 = udiv669_cast_cast_fu_338_p3;

assign empty_266_fu_327_p1 = udiv671_cast_cast_fu_319_p3;

assign empty_267_fu_308_p1 = udiv673_cast_cast_fu_300_p3;

assign empty_268_fu_289_p1 = udiv675_cast_cast_fu_281_p3;

assign empty_269_fu_422_p1 = udiv677_cast_cast_fu_414_p3;

assign mask664_fu_407_p2 = 4'd3 << empty_262_fu_403_p1;

assign mask666_fu_388_p2 = 4'd3 << empty_263_fu_384_p1;

assign mask668_fu_369_p2 = 4'd3 << empty_264_fu_365_p1;

assign mask670_fu_350_p2 = 4'd3 << empty_265_fu_346_p1;

assign mask672_fu_331_p2 = 4'd3 << empty_266_fu_327_p1;

assign mask674_fu_312_p2 = 4'd3 << empty_267_fu_308_p1;

assign mask676_fu_293_p2 = 4'd3 << empty_268_fu_289_p1;

assign mask678_fu_426_p2 = 4'd3 << empty_269_fu_422_p1;

assign output_buffer_0_address1 = p_cast_fu_263_p1;

assign output_buffer_0_d1 = 32'd0;

assign output_buffer_12_address1 = p_cast_fu_263_p1;

assign output_buffer_12_d1 = 32'd0;

assign output_buffer_16_address1 = p_cast_fu_263_p1;

assign output_buffer_16_d1 = 32'd0;

assign output_buffer_20_address1 = p_cast_fu_263_p1;

assign output_buffer_20_d1 = 32'd0;

assign output_buffer_24_address1 = p_cast_fu_263_p1;

assign output_buffer_24_d1 = 32'd0;

assign output_buffer_28_address1 = p_cast_fu_263_p1;

assign output_buffer_28_d1 = 32'd0;

assign output_buffer_4_address1 = p_cast_fu_263_p1;

assign output_buffer_4_d1 = 32'd0;

assign output_buffer_8_address1 = p_cast_fu_263_p1;

assign output_buffer_8_d1 = 32'd0;

assign p_cast_fu_263_p1 = empty_259_fu_258_p2;

assign tmp_reg_450 = empty;

assign tmp_s_fu_248_p4 = {{empty_257_fu_78[9:1]}};

assign udiv663_cast_cast_fu_395_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv665_cast_cast_fu_376_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv667_cast_cast_fu_357_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv669_cast_cast_fu_338_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv671_cast_cast_fu_319_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv673_cast_cast_fu_300_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv675_cast_cast_fu_281_p3 = {{empty_258_fu_244_p1}, {1'd0}};

assign udiv677_cast_cast_fu_414_p3 = {{empty_258_fu_244_p1}, {1'd0}};

always @ (posedge ap_clk) begin
    Out_Tc_Min_cast_cast_cast_cast_cast_reg_459[63] <= 1'b0;
end

endmodule //My_Conv_Write_Output_F_Pipeline_5
