# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_program/pynq_lenet5/vivado_t1/lenet3/lenet3/lenet2.srcs/sources_1/bd/design_1/ip/design_1_Dense_0_0/design_1_Dense_0_0.xci
# IP: The module: 'design_1_Dense_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_program/pynq_lenet5/vivado_t1/lenet3/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_Dense_0_0/constraints/Dense_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Dense_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Vivado_program/pynq_lenet5/vivado_t1/lenet3/lenet3/lenet2.srcs/sources_1/bd/design_1/ip/design_1_Dense_0_0/design_1_Dense_0_0.xci
# IP: The module: 'design_1_Dense_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_program/pynq_lenet5/vivado_t1/lenet3/lenet3/lenet2.gen/sources_1/bd/design_1/ip/design_1_Dense_0_0/constraints/Dense_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Dense_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
